#name: Pull Request Reminder
#
#on:
#  # https://crontab.guru/
#  schedule:
#    - cron: "5 2,7 * * 1-5"
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python 3.9
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.9"
#
#      # Installing dependencies
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      # Run the python file
#      - name: run pull_request_reminder.py
#        run: |
#          python ./job/pull_request_reminder/pull_request_reminder.py --slack-notification on
